### ISSUE TITLE
Не запускается приложение, подозрение на проблему с jar файлом

### ISSUE THREAD

**Issue by yoursalex** [yoursalex/HomeWorkAqaDocker#1]
### Возникают ошибки при запуске jar и при попытке получить от сервера ответ
Jar файл, судя по всему, полностью не запускается

### Шаги: 
* открываю сессию в play with docker
* копирую в файл application.properties ip сессии 
* выполняю команду git clone git@github.com:yoursalex/HomeWorkAqaDocker.git
* cd HomeAqaDocker , затем cd data
* apk add openjdk8
* docker-compose up -d
* java -jar db-api.jar 

* создаю еще одну сессию 
* в ней пыталась использовать команды: 
    * curl 192.168.0.33:9999/api/cards
    * curl 192.168.0.33:5432/api/cards

### Ожидаемый результат: 
доступ к данным
### Фактический результат: 
При запуске jar вижу ошибку: 
![Ошибка](https://content.screencast.com/users/yours_alex/folders/Jing/media/b2b5a906-8321-422b-a28f-62a21909a626/2019-11-24_1421.png)

При попытке запустить приложение в новом окне, вижу такие результаты: 
![Ошибка2](https://content.screencast.com/users/yours_alex/folders/Jing/media/516471a2-9653-4013-9a91-f63c720ce847/2019-11-24_1424.png)

**Comment by ArRomanov** [comment]
Похоже, что у вас проблема с подключением приложения к базе данных.
1. Нужно сначала склонировать репозиторий в том виде, в котором он есть. 
2. Затем запустить контейнер **docker-compose up -d**, проверить, что контейнер запустился и готов к приему соединений **docker-compose logs -f db**, затем выйти из режима логов **ctrl+C**
3. С помощью текстового редактора в консоли (vi) отредактировать application.properties и поставить адрес, по которому у вас запущена база данных. Либо изначально прописать вместо ip _localhost_ (не забыв указать порт) и закомитить изменения.
4. Запустить jar файл и убедиться, что приложение запустилось без ошибок.
5. Открыть новую сессию и по ip предыдущей сессии и порту 9999 попытаться получить данные по api.

Возможно и вы сделали все верно и ситуация достаточно прозаична - у вас не совпадают данные для подключения к базе данных - в docker-compose.yml у вас одни данные для создания базы, а в файле application.properties совсем другие для подключения
